### ISSUE TITLE
forward beamformer 

### ISSUE THREAD

**Issue by sunjunlishi** [zhr1201/Multi-channel-speech-extraction-using-DNN#1]
do you supply code?

**Comment by zhr1201** [comment]
Sorry but I can't upload the original beamforming code because that is part of our project with a company. 

However, this part is quite simple and a reference can be found at http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=1164847
with less than 20 lines of code and a little effort tuning the reg factor, sure you will get that to work.

Other beamforming methods like MVDR, even blind source separation, can also serve as the first stage enhancement (but not delay and sum because its directivity is poor) and some of the code can be found at GitHub.

**Comment by sunjunlishi** [comment]
ok thank you

**Comment by sunjunlishi** [comment]
i am poor on it,could you supply the code,please.
